### ISSUE TITLE
[회의록] 10/26 (목) 회의

### ISSUE THREAD

**Issue by SeoSang** [SeoSang/team_vv#18]
# 지난 회의(10/19) 때 한 것

- 디자인 시안 관련 논의
  - 시안별 고려사항 
  - 26일까지 일러스트 시안
- 개발 일정 및 준비하고 있을 것 설정
- 이슈관리 툴 논의 
  - notion 무료 블록이 너무 적음  ->  Github Project 쓰기로 결정

# 이번 회의 논의사항 (예정)

- 시안 확정
- 에셋별 의존성, 특이사항 
- UI/UX 와이어프레임 공유

# 이번 회의 논의한 것

## 에셋별 Z-index 논의

- 각 부위별 Z-index 를 가진다.
- 한 부위 내에서는 입력한 순서대로 

## 서비스 플로우

- 기본적인 서비스 플로우 공유
- 사진을 꾸미는 옵션?

### 논의해볼 것들

- 한 부위에서 앞레이어 뒤레이어 부분이 동시에 존재할 수 있는 것들 (헤어 같은 경우)
- 멀티 셀렉트 가능한 요소에서 겹침 처리 어떻게 처리할 지 기획
- 서비스 플로우에서 사진을 꾸미는 옵션?

# 다음 회의까지의 목표

## 디자인
- 시안 A, B 에 대해 결정하기

## 개발
- DB 설정
  -  DB 임의의 API 구현해보기
- 화면 flow 보고 필요한 API 정리해보기

# 다음에 고려해볼 것들
-

**Comment by hyperfection** [comment]
인스타그램 만들어서 광고돌리기

**Comment by hyperfection** [comment]
멀티 셀렉트 가능한 요소에서 겹침 처리 어떻게 처리할 지 기획
=> "tag"를 붙여서 

"안경" 안경끼리는 서로 밀어내도록
"귀걸이" 귀걸이끼리는 서로 밀어내도록

**Comment by hyperfection** [comment]
이미지 로딩이 느림 + 블링크현상?

**Comment by hyperfection** [comment]
회의 날짜 바꾸기 (월 목 제외) - 수빈의 개인 사정에 의해
